"""Regenerates core/sin_lut.inc: 257 samples of one sine period (the last equals the first)."""
import math

vals = [math.sin(2 * math.pi * i / 256) for i in range(257)]
rows = ["    " + ", ".join(f"{v:.9f}f" for v in vals[i : i + 8]) + "," for i in range(0, 257, 8)]
with open("core/sin_lut.inc", "w") as f:
    f.write("/* generated by tools/gen_lut.py: sin(2*pi*i/256), i = 0..256 */\n" + "\n".join(rows) + "\n")
